#!/usr/bin/env bash

isinstalled router.py || exit

lvl="$(router.py)"

[ "$lvl" -le 30 ] && notify-send -u critical "Router low battery!" "$lvl%" && echo "R: (!) $lvl%"
[ "$lvl" -gt 30 ] && [ "$lvl" -lt 98 ] && echo "R: $lvl%"
[ "$lvl" -gt 98 ] && echo "R: FULL $lvl%"
