#!/usr/bin/env bash

isinstalled youtube-dl

usage() {
    echo -e "Options: \n- vid \n- song \n- song-np to download one song instead of entire playlist"
    exit 1
}

case "$1" in
    vid) youtube-dl -i -x -f bestaudio/best "$2" ;;
    song) youtube-dl -i -x --audio-format mp3 "$2" ;;
    songNp) youtube-dl -i -x --audio-format mp3 "$2" --no-playlist ;;
    *) usage
    ;;
esac
