#!/usr/bin/env bash

isinstalled yt-dlp

usage() {
    echo -e "Options: \n- vid \n- song \n- song-np to download one song instead of entire playlist"
    exit 1
}

case "$1" in
    vid) yt-dlp -i -x -f bestaudio/best "$2" ;;
    song) yt-dlp -i -x --audio-format mp3 "$2" ;;
    songNp) yt-dlp -i -x --audio-format mp3 "$2" --no-playlist ;;
    *) usage
    ;;
esac
