#!/usr/bin/env bash

isinstalled skim || exit 1

scriptsDir="$HOME/.local/sc"

cd "$scriptsDir" || exit 1

du -a "$scriptsDir"/* | 
    awk '{print $2}' | 
    sk --reverse --height 15 | 
    xargs -r "$EDITOR"
